project:
  type: website
  output-dir: docs

format:
  html:
    anchor-sections: true
    math: mathjax
    include-in-header:
      text: |
        <script type="text/javascript">
        MathJax = {
          tex: {
            macros: {
              indep: "\\perp\\!\\!\\!\\perp",
              notindep: "\\not\\!\\!\\perp\\!\\!\\!\\perp"
            }
          }
        };
        </script>
    toc: true
    # toc-title: Contents
    # toc-expand: 2
    # toc-location: left
    code-fold: true
    code-line-numbers: true
    css: styles/custom.scss

bibliography: refs/references.bib
csl: refs/chicago-author-date.csl

execute:
  echo: true
  warning: false
  message: false